
server:
  port: ${port:8081}

spring:
  kafka:
#    retry:
#      topic:
#        enabled: true
#        attempts: 3
    listener:
      ack-mode: RECORD  #default é BATCH
      missing-topics-fatal: true
    consumer:
      bootstrap-servers:    #default
        - localhost:9092
      group-id: ${group-id:grupo-01}
      properties:
        allow.auto.create.topics: false   #bloqueia a criação de tópicos no consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  #default
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  #default

