server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   #resolve incompability between swagger and spring-boot
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer    #default
      value-serializer: org.apache.kafka.common.serialization.StringSerializer    #default
